# Generated by Django 6.0.1 on 2026-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0006_delete_booking_delete_meetingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date the current lease started.', null=True),
        ),
    ]
